import type { Connector, ValidationPhase, ValidationRun } from "./types";

export const validationPhases: ValidationPhase[] = [
  {
    id: "phase-0",
    number: "0",
    title: "Background warmup",
    timeframe: "Starts day one",
    gate: "Separate sending domain, DNS authentication, warmup, and list build are started.",
    gateStatus: "blocked",
    tasks: [
      {
        id: "p0-domain-warmup",
        phaseId: "phase-0",
        label: "Start cold-email domain warmup",
        category: "external",
        status: "blocked_external_account",
        owner: "User",
        notes:
          "Requires buying or assigning a sending domain, configuring SPF/DKIM/DMARC, and beginning a 2-6 week warmup.",
        evidence: "Domain, DNS records, mailbox warmup log, and verified list source.",
      },
    ],
  },
  {
    id: "phase-1",
    number: "1",
    title: "Prove the engine runs",
    timeframe: "1-2 days",
    gate:
      "The skill installs, triggers on its own, and produces a full package on one real pillar.",
    gateStatus: "ready",
    tasks: [
      {
        id: "p1-install-skill",
        phaseId: "phase-1",
        label: "Install the .skill in Settings, Capabilities, Skills",
        category: "external",
        status: "ready_for_execution",
        owner: "User",
        notes: "Execution steps are represented in the dashboard and docs.",
        evidence: "Screenshot or note confirming the installed skill.",
      },
      {
        id: "p1-trigger-test",
        phaseId: "phase-1",
        label: "Trigger with 'help me distribute this post' without naming the skill",
        category: "external",
        status: "ready_for_execution",
        owner: "User",
        notes:
          "Record whether the four-mode engine fires without explicit skill naming.",
        evidence: "Chat transcript or screenshot showing the trigger result.",
      },
      {
        id: "p1-trigger-tuning",
        phaseId: "phase-1",
        label: "Tune skill description and retest if undertriggering",
        category: "repo",
        status: "docs_complete_pending_execution",
        owner: "MarketMaster",
        notes: "The remediation path is documented; actual tuning depends on the trigger result.",
        evidence: "Before/after skill description and retest transcript.",
      },
      {
        id: "p1-code-execution",
        phaseId: "phase-1",
        label: "Confirm Code Execution state for script handling",
        category: "external",
        status: "ready_for_execution",
        owner: "User",
        notes:
          "The tracker records both script-enabled and manual validation modes.",
        evidence: "Code Execution on/off decision record.",
      },
      {
        id: "p1-manual-fallback",
        phaseId: "phase-1",
        label: "Test the manual fallback path",
        category: "repo",
        status: "docs_complete_pending_execution",
        owner: "MarketMaster",
        notes: "Manual fallback runbook is included in docs/manual-fallbacks.md.",
        evidence: "Manual run output and acceptability notes.",
      },
      {
        id: "p1-diagnose",
        phaseId: "phase-1",
        label: "Run Diagnose on one real piece of content",
        category: "external",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Requires a real pillar or post from the business.",
        evidence: "Diagnose output attached to a real content artifact.",
      },
      {
        id: "p1-atomize",
        phaseId: "phase-1",
        label: "Run Atomize on the same piece",
        category: "external",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Uses the same real pillar as the Diagnose run.",
        evidence: "Generated email, social, carousel, and clip assets.",
      },
      {
        id: "p1-buyer-read",
        phaseId: "phase-1",
        label: "Read output as a buyer and note generic, off-voice, or thin spots",
        category: "human",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "This is a human quality review, not an automated pass.",
        evidence: "QA notes with copy misses and voice fixes.",
      },
    ],
  },
  {
    id: "phase-2",
    number: "2",
    title: "Prove each distribution path",
    timeframe: "1-2 weeks",
    gate: "Every connector either executes live or has a documented manual fallback.",
    gateStatus: "blocked",
    tasks: [
      {
        id: "p2-list-form",
        phaseId: "phase-2",
        label: "Stand up a real email list and signup form",
        category: "external",
        status: "blocked_external_account",
        owner: "User",
        notes: "Needs Mailchimp, Brevo, or equivalent account access.",
        evidence: "Live signup form URL and list confirmation.",
      },
      {
        id: "p2-asset-destination",
        phaseId: "phase-2",
        label: "Confirm social and email assets point to the signup form",
        category: "external",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Cannot verify until the owned-audience destination exists.",
        evidence: "Links in generated email and social assets.",
      },
      {
        id: "p2-connector-matrix",
        phaseId: "phase-2",
        label: "Log pass, fail, or fallback for every connector row",
        category: "repo",
        status: "docs_complete_pending_execution",
        owner: "MarketMaster",
        notes: "Connector requirements and fallback behaviors are encoded in /channels.",
        evidence: "Each connector row updated after live or fallback testing.",
      },
    ],
  },
  {
    id: "phase-3",
    number: "3",
    title: "One full end-to-end real run",
    timeframe: "A few days",
    gate: "A real pillar goes live and has observable results.",
    gateStatus: "blocked",
    tasks: [
      {
        id: "p3-pick-pillar",
        phaseId: "phase-3",
        label: "Pick one real pillar about distribution",
        category: "human",
        status: "ready_for_execution",
        owner: "User",
        notes: "The first dogfood run should also build MarketMaster's own audience.",
        evidence: "Selected pillar title, URL, or source document.",
      },
      {
        id: "p3-run-chain",
        phaseId: "phase-3",
        label: "Run diagnose, atomize, validate, and schedule",
        category: "external",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Requires the skill and at least one channel path to be usable.",
        evidence: "Full chain transcript and scheduled asset list.",
      },
      {
        id: "p3-publish",
        phaseId: "phase-3",
        label: "Actually publish email and at least one social post",
        category: "external",
        status: "blocked_external_account",
        owner: "User",
        notes: "Requires configured email/social accounts or a clean manual publish process.",
        evidence: "Sent email proof and live social post URL.",
      },
      {
        id: "p3-capture-result",
        phaseId: "phase-3",
        label: "Capture impressions, clicks, replies, and signups",
        category: "external",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Metrics are zero/null until a real run is live.",
        evidence: "Analytics, platform metrics, or manual measurement screenshot.",
      },
      {
        id: "p3-real-action",
        phaseId: "phase-3",
        label: "Confirm one real person took one real action",
        category: "external",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "The commercial proof point depends on real audience behavior.",
        evidence: "Reply, signup, click, booked call, or other action record.",
      },
    ],
  },
  {
    id: "phase-4",
    number: "4",
    title: "Harden quality and reliability",
    timeframe: "Ongoing, few days",
    gate: "Output is client-grade without rewriting half of it.",
    gateStatus: "ready",
    tasks: [
      {
        id: "p4-copy-misses",
        phaseId: "phase-4",
        label: "Fix copy misses from Phases 1 and 3",
        category: "human",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Needs QA notes from real outputs before fixes can be made.",
        evidence: "Changed generation/voice instructions and accepted sample output.",
      },
      {
        id: "p4-document-fallbacks",
        phaseId: "phase-4",
        label: "Document every manual fallback",
        category: "repo",
        status: "docs_complete_pending_execution",
        owner: "MarketMaster",
        notes: "Fallback runbook is present; connector-specific evidence still needs live testing.",
        evidence: "docs/manual-fallbacks.md plus connector evidence rows.",
      },
      {
        id: "p4-run-second",
        phaseId: "phase-4",
        label: "Run the full engine a second time on different content",
        category: "external",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Repeat run validates consistency.",
        evidence: "Second run transcript, outputs, and QA notes.",
      },
      {
        id: "p4-run-third",
        phaseId: "phase-4",
        label: "Run a third time and confirm consistency",
        category: "external",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Confirms the first good run was not a fluke.",
        evidence: "Third run transcript, outputs, and consistency notes.",
      },
    ],
  },
  {
    id: "phase-5",
    number: "5",
    title: "Readiness checklist",
    timeframe: "Can-sell gate",
    gate: "All readiness claims are true before anything is sold.",
    gateStatus: "blocked",
    tasks: [
      {
        id: "p5-trigger",
        phaseId: "phase-5",
        label: "Skill triggers reliably and produces a full package on demand",
        category: "external",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Depends on Phase 1 live trigger evidence.",
        evidence: "Repeatable trigger transcript.",
      },
      {
        id: "p5-email-social",
        phaseId: "phase-5",
        label: "Email drafts and one social channel publish for real",
        category: "external",
        status: "blocked_external_account",
        owner: "User",
        notes: "Requires email/social connector or manual publish access.",
        evidence: "Sent campaign and live social URL.",
      },
      {
        id: "p5-list",
        phaseId: "phase-5",
        label: "A real list captures subscribers and every asset funnels to it",
        category: "external",
        status: "blocked_external_account",
        owner: "User",
        notes: "Requires the owned-audience destination from Phase 2.",
        evidence: "Signup form URL and subscriber capture proof.",
      },
      {
        id: "p5-measured-pillar",
        phaseId: "phase-5",
        label: "One full pillar has gone live and produced measurable engagement",
        category: "external",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Cannot be passed until Phase 3 has live metrics.",
        evidence: "Impressions, clicks, replies, signups, or equivalent engagement.",
      },
      {
        id: "p5-copy-quality",
        phaseId: "phase-5",
        label: "Copy is good enough to send to a client unedited",
        category: "human",
        status: "awaiting_real_world_evidence",
        owner: "User",
        notes: "Human judgment gate after repeated real outputs.",
        evidence: "Accepted unedited output sample.",
      },
      {
        id: "p5-measurement",
        phaseId: "phase-5",
        label: "Measurement produces real numbers you can read back",
        category: "external",
        status: "blocked_external_account",
        owner: "User",
        notes: "Requires GA4, Supermetrics, platform analytics, or manual metric capture.",
        evidence: "Analytics dashboard or exported metrics.",
      },
      {
        id: "p5-outbound",
        phaseId: "phase-5",
        label: "Cold outbound has warmed and sent one real sequence",
        category: "external",
        status: "blocked_external_account",
        owner: "User",
        notes: "Warmup has a 4-6 week floor and cannot be accelerated in code.",
        evidence: "Warmup completion and first sequence send proof.",
      },
    ],
  },
];

export const connectors: Connector[] = [
  {
    id: "mailchimp-brevo",
    name: "Mailchimp or Brevo",
    category: "email",
    actionNeeded: "Create a real draft campaign and send a test to yourself.",
    status: "held_action",
    liveCapability: "Mailchimp connector is available for draft creation and analytics.",
    fallbackBehavior: "Generate the campaign copy and checklist for manual draft creation.",
    credentialHint: "User go-ahead is required before creating drafts or sending tests.",
    notes:
      "Default-branch tracker records this as held because draft/test-send is outward-facing.",
  },
  {
    id: "linkedin",
    name: "LinkedIn via Buffer, Zapier, or manual",
    category: "social",
    actionNeeded: "Queue and publish one real post.",
    status: "fallback_ready",
    liveCapability: "Queue through Buffer/Zapier when connected.",
    fallbackBehavior: "Copy-ready post with manual scheduling steps.",
    credentialHint: "Buffer/Zapier account or LinkedIn admin access.",
    notes: "Direct LinkedIn API access is limited; manual remains acceptable.",
  },
  {
    id: "x-social",
    name: "X or other social",
    category: "social",
    actionNeeded: "Queue and publish one real post.",
    status: "fallback_ready",
    liveCapability: "Queue through a supported social scheduler.",
    fallbackBehavior: "Copy-ready post, link, image notes, and manual publish record.",
    credentialHint: "Social scheduler or platform account access.",
    notes: "Treat direct API write access as unproven until tested.",
  },
  {
    id: "ahrefs-semrush",
    name: "Ahrefs or Semrush",
    category: "seo",
    actionNeeded: "Pull real keyword and AI-citation data to shape a pillar.",
    status: "plan_blocked",
    liveCapability: "Use paid SEO data for query/citation inputs after plan access is upgraded.",
    fallbackBehavior: "Manual SERP review and documented assumptions.",
    credentialHint: "Ahrefs plan is insufficient; Semrush MCP access is not included on the current plan.",
    notes:
      "Recorded probe result: both keyword data paths are plan-blocked until upgraded or scoped to manual fallback.",
  },
  {
    id: "canva",
    name: "Canva",
    category: "creative",
    actionNeeded: "Produce one real carousel from the slide outline.",
    status: "live",
    liveCapability: "Create a Canva design when app access is connected.",
    fallbackBehavior: "Slide outline, frame notes, and manual design QA checklist.",
    credentialHint: "Canva is authenticated; add a brand kit before judging client-grade output.",
    notes: "Recorded probe result: Canva is live with the caveat that 0 brand kits are configured.",
  },
  {
    id: "higgsfield",
    name: "Higgsfield",
    category: "creative",
    actionNeeded: "Produce one real short-form clip from the script.",
    status: "live",
    liveCapability: "Generate a clip when model access is connected.",
    fallbackBehavior: "Short-form script, shot list, and manual production brief.",
    credentialHint: "Higgsfield Ultra plan is available.",
    notes: "Recorded probe result: Higgsfield is live with 2,044 credits.",
  },
  {
    id: "ga4-supermetrics",
    name: "Supermetrics or GA4",
    category: "analytics",
    actionNeeded: "Get real numbers into one view with AI-search channel grouping.",
    status: "auth_blocked",
    liveCapability: "Pull campaign metrics from analytics properties.",
    fallbackBehavior: "Manual metric capture table with source screenshots.",
    credentialHint: "GA4 is not authenticated in Supermetrics.",
    notes:
      "Recorded probe result: 0 of 172 Supermetrics sources are authenticated; GA4 is NOT_AUTHENTICATED.",
  },
  {
    id: "apollo",
    name: "Apollo",
    category: "outbound",
    actionNeeded: "Build sequence; sending waits on warmup.",
    status: "held_action",
    liveCapability: "Build and send sequence after domain warmup clears.",
    fallbackBehavior: "Sequence copy and targeting criteria documented for later import.",
    credentialHint: "Apollo is authenticated; sending still needs a warmed domain.",
    notes:
      "Recorded probe result: Apollo can build sequences with 2,500 lead credits and 250k AI credits.",
  },
];

export const validationRuns: ValidationRun[] = [
  {
    id: "run-001",
    name: "Distribution dogfood pillar",
    status: "planned",
    summary:
      "First end-to-end run is planned against MarketMaster's own distribution content.",
    evidence: [
      "Real pillar selected",
      "Diagnose and Atomize outputs attached",
      "Email/social publishing proof",
      "Metrics readback",
    ],
    metrics: {
      impressions: null,
      clicks: null,
      replies: null,
      signups: null,
    },
  },
];

export const constraints = [
  "Outbound warmup is a 4-6 week floor and cannot be made green by code.",
  "Paid connectors must be scoped to the plans and credentials actually available.",
  "Social automation should be treated as manual or scheduler-based until proven.",
  "Copy quality remains a human judgment gate after real outputs exist.",
];
